# Generated by Django 4.1.4 on 2022-12-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
